name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: railway
      url: https://cineguru-production.up.railway.app/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Railway
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
